apiVersion: v1
kind: Service
metadata:
  name: hardhat-node
  namespace: blockchain
spec:
  selector:
    app: hardhat-node
  ports:
  - port: 8545
    targetPort: 8545
    protocol: TCP
  type: ClusterIP

