apiVersion: v1
kind: Service
metadata:
  name: ipfs-service
  namespace: sharing-sbom-system
spec:
  selector:
    app: ipfs-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP

