apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs-service
  namespace: sharing-sbom-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipfs-service
  template:
    metadata:
      labels:
        app: ipfs-service
    spec:
      containers:
      - name: ipfs-service
        image: ghcr.io/tuberlin-blockchain-prototyping/sharing-sbom-system/ipfs-service:e4c33f6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: IPFS_HOST
          value: "ipfs-node"
        - name: IPFS_PORT
          value: "5001"
        - name: IPFS_PROTOCOL
          value: "http"
        - name: DB_PATH
          value: "/data/ipfs.db"
        volumeMounts:
        - name: ipfs-service-data
          mountPath: /data
      volumes:
      - name: ipfs-service-data
        emptyDir: {}
