apiVersion: apps/v1
kind: Deployment
metadata:
  name: merkle-proof-service
  namespace: sharing-sbom-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merkle-proof-service
  template:
    metadata:
      labels:
        app: merkle-proof-service
    spec:
      containers:
      - name: merkle-proof-service
        image: ghcr.io/tuberlin-blockchain-prototyping/sharing-sbom-system/merkle-proof-service:6c0e0b2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8090
          name: http
        env:
        - name: PORT
          value: "8090"
        - name: GIN_MODE
          value: "release"
        volumeMounts:
        - name: merkle-proof-service-data
          mountPath: /app/data
      volumes:
      - name: merkle-proof-service-data
        emptyDir: {}

