apiVersion: apps/v1
kind: Deployment
metadata:
  name: proving-service
  namespace: sharing-sbom-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proving-service
  template:
    metadata:
      labels:
        app: proving-service
    spec:
      containers:
      - name: proving-service
        image: ghcr.io/tuberlin-blockchain-prototyping/sharing-sbom-system/proving-service:6c0e0b2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: RUST_LOG
          value: "info"
