apiVersion: v1
kind: Service
metadata:
  name: verifier-service
  namespace: sharing-sbom-system
spec:
  selector:
    app: verifier-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP

